internal: disable tests in prerelease, rename repository in workflows (#3)

diff --git a/packages/vibe-storybook-components/.github/workflows/prerelease.yml b/packages/vibe-storybook-components/.github/workflows/prerelease.yml
--- a/packages/vibe-storybook-components/.github/workflows/prerelease.yml
+++ b/packages/vibe-storybook-components/.github/workflows/prerelease.yml
@@ -25,21 +25,22 @@ jobs:
         run: |
           git config --global user.name 'ci'
           git config --global user.email 'deploy@monday.com'
-      - name: "Wait for tests to succeed"
-        uses: fountainhead/action-wait-for-check@v1.1.0
-        if: success()
-        id: wait-for-tests
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: "test"
-          ref: ${{ github.event.pull_request.head.sha || github.sha }}
-          timeoutSeconds: 1200
-          intervalSeconds: 20
-      - name: "Tests failed - exit"
-        if: steps.wait-for-tests.outputs.conclusion != 'success'
-        run: |
-          echo "::error::test check failed - prerelease cancelled"
-          exit 1
+      #          TODO tests are disabled for now
+      #      - name: "Wait for tests to succeed"
+      #        uses: fountainhead/action-wait-for-check@v1.1.0
+      #        if: success()
+      #        id: wait-for-tests
+      #        with:
+      #          token: ${{ secrets.GITHUB_TOKEN }}
+      #          checkName: "test"
+      #          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      #          timeoutSeconds: 1200
+      #          intervalSeconds: 20
+      #      - name: "Tests failed - exit"
+      #        if: steps.wait-for-tests.outputs.conclusion != 'success'
+      #        run: |
+      #          echo "::error::test check failed - prerelease cancelled"
+      #          exit 1
       - name: Create Updated version
         id: create-update-version
         if: success()
@@ -74,7 +75,7 @@ jobs:
 
             ```
             // To install this prerelease version using npm, please run the following command in your terminal:
-            npm i monday-ui-storybook-blocks@${{ steps.create-update-version.outputs.package_version }}
+            npm i vibe-storybook-components@${{ steps.create-update-version.outputs.package_version }}
             // If you prefer using Yarn, you can use the following command instead:
-            yarn add monday-ui-storybook-blocks@${{ steps.create-update-version.outputs.package_version }}
+            yarn add vibe-storybook-components@${{ steps.create-update-version.outputs.package_version }}
             ```
